In [1]:
import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Thu thập và tiền xử lý với bài tập

* Lấy data:
    * code tìm ra email với số điều kiện nword
    * lọc tay ra email tương ứng và chỉnh lại số thứ tự

# Loading data

In [11]:
data_700_email = []
data_700_email = pd.read_csv("https://raw.githubusercontent.com/DangCao1999/ML-Study/master/BaiHoc/Naive%20Bayes/Spam%20email%20data/train-features-700.txt",  sep=" ", header=None)
data_700_email.head()

   0   1  2
0  1  19  2
1  1  45  1
2  1  50  1
3  1  75  1
4  1  85  1

In [24]:
label_700_email = []
label_700_email = pd.read_csv("https://raw.githubusercontent.com/DangCao1999/ML-Study/master/BaiHoc/Naive%20Bayes/Spam%20email%20data/train-labels-700.txt",  sep=" ", header=None)
label_700_email.head()

   0
0  0
1  0
2  0
3  0
4  0

# Find email with number nword

In [32]:
def findEmailWithNumberNword(numberNWord):
    data_700_email_np = data_700_email.values
    data100Nword = []
    data_filter = {}
    for word in data_700_email_np:
        if(data_filter.get((word[0])) == None):
            data_filter[word[0]] = [word[1]]
        else:
            data_filter[word[0]].append(word[1])

        
    for keyEmail in data_filter:
        find = True
        for value in data_filter[keyEmail]:
            if(value > numberNWord):
                find = False
                break
        if(find):
            data100Nword.append(keyEmail)
        
    print(data100Nword)
    return data100Nword

In [35]:
findEmailWithNumberNword(100)
findEmailWithNumberNword(500)
numberEmailFilter = findEmailWithNumberNword(1000)

[]
[]
[73, 152, 169, 176, 255, 383, 415, 489, 524, 591, 625]

In [55]:
emailFiltered = pd.DataFrame();
for emailNumber in numberEmailFilter:
    dataFrame = data_700_email[data_700_email[0] == emailNumber]
    dataFrame[1].replace([0], inplace=True)
    emailFiltered = emailFiltered.append(dataFrame)
emailFiltered

6037    73
6038    73
6039    73
6040    73
6041    73
6042    73
6043    73
6044    73
6045    73
6046    73
6047    73
6048    73
6049    73
6050    73
6051    73
6052    73
6053    73
Name: 0, dtype: int64
12096    152
12097    152
12098    152
12099    152
12100    152
12101    152
12102    152
12103    152
12104    152
Name: 0, dtype: int64
13464    169
13465    169
13466    169
13467    169
Name: 0, dtype: int64
13826    176
13827    176
13828    176
13829    176
13830    176
13831    176
13832    176
13833    176
13834    176
13835    176
13836    176
13837    176
13838    176
13839    176
13840    176
13841    176
13842    176
13843    176
13844    176
13845    176
13846    176
13847    176
13848    176
Name: 0, dtype: int64
22512    255
22513    255
22514    255
22515    255
22516    255
22517    255
22518    255
22519    255
22520    255
22521    255
22522    255
22523    255
Name: 0, dtype: int64
39191    383
39192    383
39193    383
39194    383
39195    383
39196    383
39197    383
39198    383
39199    383
39200    383
39201    383
39202    383
39203    383
Name: 0, dtype: int64
42238    415
42239    415
42240    415
42241    415
42242    415
42243    415
42244    415
42245    415
42246    415
42247    415
42248    415
Name: 0, dtype: int64
53056    489
53057    489
53058    489
53059    489
53060    489
53061    489
53062    489
53063    489
53064    489
Name: 0, dtype: int64
57880    524
57881    524
57882    524
57883    524
57884    524
57885    524
Name: 0, dtype: int64
69045    591
69046    591
69047    591
69048    591
69049    591
69050    591
69051    591
69052    591
69053    591
69054    591
69055    591
69056    591
69057    591
69058    591
69059    591
69060    591
69061    591
69062    591
69063    591
69064    591
69065    591
Name: 0, dtype: int64
72409    625
72410    625
72411    625
72412    625
72413    625
72414    625
72415    625
72416    625
Name: 0, dtype: int64

         0    1  2
6037    73    4  1
6038    73   29  1
6039    73   35  1
6040    73   45  3
6041    73   56  1
...    ...  ... ..
72412  625  285  1
72413  625  529  1
72414  625  569  1
72415  625  705  1
72416  625  957  1

[133 rows x 3 columns]

# Sparse Matrix

In [7]:
nwords = 2500
nemails = 20
rows = data_feature[0] -1 
cols = data_feature[1] -1 
data = data_feature[2]
coo_data = coo_matrix((data, (rows, cols)), shape=(nemails, nwords)).toarray()

In [8]:
print(data_feature[0])

0        1
1        1
2        1
3        1
4        1
        ..
1659    20
1660    20
1661    20
1662    20
1663    20
Name: 0, Length: 1664, dtype: int64

In [9]:
data_label1 = []
data_label1 = pd.read_csv("https://raw.githubusercontent.com/DangCao1999/ML-Study/master/BaiHoc/Naive%20Bayes/Spam%20email%20data/train-features-700.txt", sep=" ", header=None)

In [10]:
print(data_label1[data_label1[1] < 100])

         0   1  2
0        1  19  2
1        1  45  1
2        1  50  1
3        1  75  1
4        1  85  1
...    ...  .. ..
79895  700  91  1
79896  700  93  3
79897  700  94  4
79898  700  95  3
79899  700  96  1

[16197 rows x 3 columns]